# Generated by Django 5.2.5 on 2025-10-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDCApp1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
        migrations.AddField(
            model_name='mascota',
            name='identificacion',
            field=models.CharField(default='sin_id', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
