# Generated by Django 5.1.4 on 2025-10-07 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDCApp1', '0003_alter_mascota_identificacion_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_cliente', models.CharField(max_length=12)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('id_mascota', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='run',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
