# Generated by Django 5.1.4 on 2025-10-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDCApp1', '0004_adopcion_profile_apellido_profile_run'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adopcion',
            old_name='fecha',
            new_name='fecha_adopcion',
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='detalle',
            field=models.TextField(default='Sin detalle'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='run_cliente',
            field=models.CharField(max_length=20),
        ),
    ]
