# Generated by Django 5.1.4 on 2025-10-21 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDCApp1', '0005_rename_fecha_adopcion_fecha_adopcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_cliente', models.CharField(max_length=10, unique=True, verbose_name='RUN Cliente')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('correo', models.TextField(verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=12, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Usuario')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
            ],
            options={
                'verbose_name': 'Usuario Registrado',
                'verbose_name_plural': 'Usuarios Registrados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AlterModelOptions(
            name='adopcion',
            options={'ordering': ['-fecha_adopcion'], 'verbose_name': 'Adopción', 'verbose_name_plural': 'Adopciones'},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'verbose_name': 'Mascota', 'verbose_name_plural': 'Mascotas'},
        ),
        migrations.AddField(
            model_name='mascota',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(verbose_name='Detalle de la Solicitud')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('nombre_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='PDCApp1.mascota', verbose_name='Mascota')),
                ('run_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='PDCApp1.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-fecha'],
            },
        ),
    ]
